apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blog
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog
    spec:
      containers:
      - image: ghost:2.6-alpine
        name: ghost
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://exampleblog.com
        resources: {}
status: {}
