apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blog
  name: blog
spec:
  ports:
  - name: 80-2368
    port: 80
    protocol: TCP
    targetPort: 2368
  selector:
    app: blog
  type: NodePort
status:
  loadBalancer: {}
